[Front end] Add testing dependecies
canonical-web-and-design/greenhouse-exporter pull request #53
Opened 2021-09-20 09:59 UTC by andesol

## Done
Added
- Jest
- Testing Library
- [msw](https://mswjs.io/) (for mocking api calls)
## QA
- Run `yarn test-js` and see the test passes
- `dotrun --env DEBUG_USER_EMAIL=peter.mahnke@canonical.com`
- Verify everything is still running in `http://localhost:8501/`

2021-09-20 13:19 UTC, anthonydillon commented
@hatched what do you think of this set up?

2021-09-20 15:21 UTC, hatched commented
`prettier` is installed but it doesn't look like it's being run, I created an [issue](https://github.com/canonical-web-and-design/greenhouse-exporter/issues/55) for a follow-up

2021-09-20 15:36 UTC, hatched requested changes
Thanks for adding some tests here! I'd like it to be a bit more robust around the API response types though.

2021-09-20 15:36 UTC, hatched commented on static/js/mocks/handlers.js
> +const items = [{ job: "Web Engineer", applications: 10 }];
Can you convert this file to TS plz.

You'll want to ensure that the interface of this data type that's used in the component is the same interface that is being mocked in the tests. In other projects we use [fishery](https://www.npmjs.com/package/fishery) for this. You will probably want to evaluate that later on.

I see that the API calls in the components are not currently typed so you'll want to create a shared type and use it in both places.

2021-09-20 15:36 UTC, hatched commented on static/js/components/Dashboard/Dashboard.tsx
>  export const Dashboard: React.FC<any> = () => {
You don't need to type components with `React.FC` any longer. This can simply be the following if you don't have any props defined.

```suggestion
export const Dashboard = () => {
```

See https://github.com/facebook/create-react-app/pull/8177 for more information

2021-09-20 17:16 UTC, andesol commented
Maybe we should block this until we deal with #56

2021-09-20 17:28 UTC, hatched commented
> Maybe we should block this until we deal with #56

Yeah that's probably for the best - I didn't want to block your forward progress so I created it as a follow-up :)

2021-09-22 11:16 UTC, andesol commented on static/js/mocks/handlers.js
> +const items = [{ job: "Web Engineer", applications: 10 }];
Done. At this early stage we don't really know the types we need yet, so keeping your recommendation for later!

2021-09-22 11:17 UTC, andesol commented on static/js/components/Dashboard/Dashboard.tsx
>  export const Dashboard: React.FC<any> = () => {
:+1:

2021-09-22 11:19 UTC, andesol commented
Ready for review!

2021-09-22 15:45 UTC, hatched approved these changes
👌

2021-09-24 10:10 UTC, merged